---
- name: Install java
  homebrew_cask: name=java state=present
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

- name: Install java development tools
  homebrew: name={{item}} state=present
  with_items:
    - maven
    - tomcat

- name: Install IntelliJ
  homebrew_cask: name={{item}} state=present
  with_items:
    - intellij-idea
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
