---
- name: Install cli packages
  homebrew: name={{item}} state=present
  with_items:
    - fish
    - readline
    - wget
    - the_silver_searcher
    - coreutils
    - git
    # - rcm # tap thoughtbot/formulae first
    - watch
    - exiftool
    - youtube-dl
